---
- name: Backup /etc directory to /backups
  hosts: "{{ host }}"
  become: yes  # This will apply sudo for all tasks
  vars:
    rsync_user: "sync"  # Change this to the actual user executing the rsync command

  tasks:
    - name: Ensure the /backups directory exists
      file:
        path: "{{ backup_path }}"
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Add rsync to sudoers for password-less execution
      lineinfile:
        path: /etc/sudoers
        state: present
        insertafter: 'EOF'
        regexp: '^{{ rsync_user }} ALL=\(ALL\) NOPASSWD: /usr/bin/rsync$'
        line: '{{ rsync_user }} ALL=(ALL) NOPASSWD: /usr/bin/rsync'
        validate: 'visudo -cf %s'
      become: yes  # Ensure we're using sudo to edit the sudoers file

  - name: Synchronize /etc to /backups/etc
    synchronize:
      src: /etc/
      dest: "{{ backup_path }}"
      recursive: yes
      delete: no
      rsync_opts:
        - "--exclude=/etc/hostname"
        - "--exclude=/etc/hosts"
      rsync_path: "sudo rsync"  # Ensure sudo is used for rsync on the remote host
    become: yes
    become_user: root
