---
- name: Backup /etc directory to /backups
  hosts: "{{ host }}"
  become: yes  # This will apply sudo for all tasks
  vars:
    rsync_user: "labadmin"  # Change this to the actual user executing the rsync command

  tasks:
    - name: Ensure the /backups directory exists
      file:
        path: "{{ backup_path }}"
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Add rsync to sudoers for password-less execution
      lineinfile:
        path: /etc/sudoers
        state: present
        insertafter: 'EOF'
        regexp: '^{{ rsync_user }} ALL=\(ALL\) NOPASSWD: /usr/bin/rsync$'
        line: '{{ rsync_user }} ALL=(ALL) NOPASSWD: /usr/bin/rsync'
        validate: 'visudo -cf %s'

    - name: Synchronize /etc to /backups/etc using rsync
      command:
        cmd: "rsync -a --exclude '/etc/hostname' --exclude '/etc/hosts' /etc/ {{ rsync_user }}@{{ inventory_hostname }}:{{ backup_path }}"
      become_user: "{{ rsync_user }}"
      delegate_to: "{{ host }}"
