---
- name: Backup  directory to /backups
  hosts: "{{ host }}"
  become: yes  # Use sudo to gain root privileges
  tasks:
    - name: Ensure the /backups directory exists
      file:
        path: "{{ backup }}"
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Synchronize /etc to /backups/etc
      synchronize:
        src: "{{ source_path }}"
        dest: "{{ backup_path }}
        recursive: yes
        delete: no  # Set to 'yes' if you want to delete extraneous files from dest that are not in src
