---
- name: Backup /etc directory to /backups
  hosts: "{{ host }}"
  vars:
    user: "labadmin"  # Set the appropriate username or parameterize as needed
  tasks:
    - name: Ensure the /backups directory exists
      file:
        path: "{{ backup_path }}"
        state: directory
        owner: root
        group: root
        mode: '0755'
    become: yes

    - name: Add rsync to sudoers for password-less execution
      lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^%{{ user }} ALL=\(ALL\) NOPASSWD: /usr/bin/rsync'
        line: '{{ user }} ALL=(ALL) NOPASSWD: /usr/bin/rsync'
        validate: 'visudo -cf %s'
      become: yes

    - name: Synchronize /etc to /backups/etc
      synchronize:
        src: "{{ source_path }}"
        dest: "{{ backup_path }}"
        recursive: yes
        delete: no  # Set to 'yes' if you want to delete extraneous files from dest that are not in src
        rsync_opts:
          - "--exclude=/etc/hostname"
          - "--exclude=/etc/hosts"
      become: yes
