---
- name: Synchronize entire directory from {{ host }} to local /tmp directory on Ansible control machine
  hosts: '{{ host }}'
  become: yes
  tasks:
    - name: Synchronize the directory to local
      synchronize:
        src: '{{ source_path }}'
        dest: '/tmp/{{ backup_folder }}'
        mode: pull
        recursive: yes

- name: Synchronize directory from Ansible control machine to {{ backup_server }}
  hosts: '{{ backup_server }}'
  become: yes
  tasks:
    - name: Synchronize the directory to remote
      synchronize:
        src: '/tmp/{{ backup_folder }}/'
        dest: '{{ backup_path }}'
        mode: push
        recursive: yes
        delete: yes  # Optionally add this to ensure the destination matches the source exactly
        owner: root
        group: root
        perms: yes  # Ensure permissions are set according to source
