---
- name: Change passwords for all non-system users including root
  hosts: "{{ host }}"
  become: true
  vars:
    min_uid: 1000
    old_password: "{{ old_password }}"  
  tasks:
    - name: Gather user facts
      ansible.builtin.getent:
        database: passwd

    - name: Change password for non-system users including root
      ansible.builtin.user:

        name: "{{ item.key }}"
        password: "{{ old_password }}"
      loop: "{{ lookup('dict', getent_passwd) }}"
      when:
        - (item.value[1] | int >= min_uid or item.key == 'root') and item.key != 'nobody' and item.key != 'labadmin'
      become: yes
    
    - name: Change password for the labadmin user
      ansible.builtin.user:
        name: "labadmin"
        password: "{{ old_password }}"
      when: item.key == 'labadmin'
      loop: "{{ lookup('dict', getent_passwd) }}"
      become: yes
